version: 2
updates:
- package-ecosystem: npm
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - JonathanTreffler
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
- package-ecosystem: npm
  directory: "/demo"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - JonathanTreffler
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.2
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.13
    - 7.13.8
